drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
drop table if exists person cascade;
create table person (id bigserial not null, firstname varchar(255) not null, lastname varchar(255) not null, primary key (id));
